version: "3.9"
services:

  nodus-init:
    build:
      context: "../"
      dockerfile: "docker/DockerfileInitNode"
    container_name: nodus-init
    environment:
      OWNER_ADDRESS: ${OWNER_ADDRESS}
      OWNER_PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
      NODE_IP: ${NODE_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: no
    networks:
      - net

  nodus-vpn:
    build:
      context: "../"
      dockerfile: "docker/DockerfileVPN"
    ports:
      - "7000:7000"
    container_name: nodus-vpn
    environment:
      OWNER_ADDRESS: ${OWNER_ADDRESS}
      OWNER_PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
      NODE_IP: ${NODE_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - net

  nodus-metrics:
    build:
      context: "../"
      dockerfile: "docker/DockerfileMetrics"
    ports:
      - "7001:7001"
    container_name: nodus-metrics
    environment:
      OWNER_ADDRESS: ${OWNER_ADDRESS}
      OWNER_PRIVATE_KEY: ${OWNER_PRIVATE_KEY}
      NODE_IP: ${NODE_IP}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - net

  nodus-db:
    image: postgres:latest
    container_name: nodus-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - net


  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=${NODE_IP}
    volumes:
      - "~/.wg-easy:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      - net

  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /etc/openvpn:/etc/openvpn
    ports:
      - "1194:1194/udp"

networks:
  net:

