version: "3.9"
services:

  nodus-http:
    build:
      context: "../"
      dockerfile: "dokcer/DockerfileHttp"
    ports:
      - "7000:7000"
    container_name: nodus-http
    restart: unless-stopped
    networks:
      - net

  nodus-init:
    build:
      context: "../"
      dockerfile: "dokcer/DockerfileInitNode"
    container_name: nodus-init
    restart: unless-stopped
    networks:
      - net

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - WG_HOST=${WG_HOST}  # Укажите свой внешний IP или домен
    volumes:
      - "~/.wg-easy:/etc/wireguard"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      - net

networks:
  net: